ùó§ùòÇùó≤ùòÄùòÅùó∂ùóºùóª 1:
Write a python program that takes an input from a user which is a sequence  
of any characters. Pass the input as an argument to a function. Your  
function should modify the given string by the user in such a way that a  
character does not exist in the string consecutively for more than 3 times  
and then return the modified string.

Sample 1 input:
aaaaabbbbccsshak,cka
Sample output 1:
aaabbbccsshak,cka

Sample 2 input:
AAAABBBBBBBBBBBB
Sample output 2:
AAABBB

In [ ]:
user_input = input("Please enter a sequence of any characters: ")

In [ ]:
# QUESTION 2

class SDS :
  def __init__(self,year,no_cse=0,no_mns=0,cse={},mns={}):
    self.year = year
    self.no_cse = no_cse
    self.no_mns = no_mns
    self.cse = cse
    self.mns = mns
    print("School of Data and Sciences", self.year + "! Only CSE and MNS department students can be added.")
    
  def addStudent(self,*args):
    self.args = args
    if args == "BBS" :
      print("BBS department student cannot be added to SDS")

  def print_info(self):
    print("Number of CSE students:", self.no_cse)
    print("Number of MNS students:", self.no_mns)
    print("CSE Students", self.cse)
    print("MNS Students", self.mns)

class Student :
  def __init__(self,name,ID,dept="MNS",course=[],cg=0):
    self.name = name
    self.ID = ID
    self.dept = dept
    self.course = course
    self.cg = cg
    

  def print_info(self):
    print("Name:", self.name)
    print("ID:", self.ID)
    print("Department:", self.dept)
    print("Courses:", self.course)
    print("CGPA:", self.cg)


# Write you code here
sds21 = SDS("2021")
print("*********************************************")
sds21.print_info()
print("1.================================")
s1 = Student("Maliha",21101001)
s1.print_info()
print("2.================================")
sds21.addStudent(s1)
sds21.print_info()
print("3.================================")
s2 = Student("Subha",21301001,"CSE", ["ENG091","MAT092"],3.48)
s2.print_info()
print("4.================================")
sds21.addStudent(s2)
sds21.print_info()
print("5.================================")
s3 = Student("Samiul",21305001,"MNS", ["ENG091","MAT092","PHY111"],3.01)
s4 = Student("Mohsina",21305023)
print("6.================================")
s3.print_info()
print("7.================================")
s4.print_info()
print("8.================================")
sds21.addStudent(s3,s4)
print("9.================================")
sds21.print_info()
print("10.================================")
s5 = Student("Nayla", 16101288, "BBS")
sds21.addStudent(s5)
print("11.================================")
sds21.print_info()

School of Data and Sciences 2021! Only CSE and MNS department students can be added.
*********************************************
Number of CSE students: 0
Number of MNS students: 0
CSE Students {}
MNS Students {}
1.================================
Name: Maliha
ID: 21101001
Department: MNS
Courses: []
CGPA: 0
2.================================
Number of CSE students: 0
Number of MNS students: 0
CSE Students {}
MNS Students {}
3.================================
Name: Subha
ID: 21301001
Department: CSE
Courses: ['ENG091', 'MAT092']
CGPA: 3.48
4.================================
Number of CSE students: 0
Number of MNS students: 0
CSE Students {}
MNS Students {}
5.================================
6.================================
Name: Samiul
ID: 21305001
Department: MNS
Courses: ['ENG091', 'MAT092', 'PHY111']
CGPA: 3.01
7.================================
Name: Mohsina
ID: 21305023
Department: MNS
Courses: []
CGPA: 0
8.================================
9.================================
Number of CSE students: 0
Number of MNS students: 0
CSE Students {}
MNS Students {}
10.================================
11.================================
Number of CSE students: 0
Number of MNS students: 0
CSE Students {}
MNS Students {}